DROP TABLE IF EXISTS USER;
  
CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
  
);

DROP TABLE IF EXISTS TBL_MEMBERS;
  
CREATE TABLE TBL_MEMBERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  age INT NOT NULL,
  phone VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  company VARCHAR(250) NULL
);